### ISSUE TITLE
Intermittent issue with the MouseMovementDetector component

### ISSUE THREAD

**Issue by caprica** [caprica/vlcj-player#12]
Seems to be caused when using the recent files menu to start video.

e.g.

    java.lang.IllegalStateException: Already started
	at uk.co.caprica.vlcjplayer.view.MouseMovementDetector.start(MouseMovementDetector.java:65)
	at uk.co.caprica.vlcjplayer.view.main.MainFrame$13.playing(MainFrame.java:431)
	at uk.co.caprica.vlcj.player.events.standard.MediaPlayerPlayingEvent.notify(MediaPlayerPlayingEvent.java:42)
	at uk.co.caprica.vlcj.player.base.EventService.raiseEvent(EventService.java:94)
	at uk.co.caprica.vlcj.player.base.EventService$MediaPlayerEventCallback.callback(EventService.java:107)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:520)
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:551)

Need to check threading here too as the event is now (with vlcj-4) delivered on the native thread.

**Comment by caprica** [comment]
Old issue, don't care anymore.
