### ISSUE TITLE
It compiles but doesn't launch 

### ISSUE THREAD

**Issue by py4object** [caprica/vlcj-player#2]
```
log4j:WARN No appenders could be found for logger (uk.co.caprica.vlcj.Info).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
    at uk.co.caprica.vlcjplayer.VlcjPlayer.<init>(VlcjPlayer.java:105)
    at uk.co.caprica.vlcjplayer.VlcjPlayer$1.run(VlcjPlayer.java:83)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.util.MissingResourceException: Can't find bundle for base name strings/vlcj-player, locale en_US
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
    at uk.co.caprica.vlcjplayer.Application.<clinit>(Application.java:46)
    ... 16 more
```

**Comment by caprica** [comment]
The app does launch, but it depends how you run it of course...

You don't have the right classpath set I would suggest, since it's looking for that resource bundle on the classpath.

There is a README that tells you how to run it.

If you do a "mvn install" it produces a distribution package. I just unzipped the package to test it. If you then following the instructions in the README to run the jar file, it does in fact work.

**Comment by py4object** [comment]
I'm really sorry for not reading the README file carefully!

However it's still not working for me ,Here is the errors stack :

```
../Java/vlcj-player/target]$ java -jar vlcj-player-1.0.0-SNAPSHOT.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: uk/co/caprica/vlcj/player/embedded/FullScreenStrategy
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: uk.co.caprica.vlcj.player.embedded.FullScreenStrategy
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more
```

**Comment by caprica** [comment]
Don't try and run that jar from the target directory, you need to unpack the zip or tgz file and run the jar from inside the unpacked directory.

**Comment by py4object** [comment]
Thanks a lot ,now my problem is gone

**Comment by py4object** [comment]
Thanks a lot ,now it's working

**Comment by mlop113** [comment]
![capture](https://user-images.githubusercontent.com/22517602/40271716-51bc9050-5bcb-11e8-99ed-447ec1f0d7a4.PNG)
 
I have this error, How i can fix this, bro?   " Caused by: java.lang.NoClassDefFoundError: uk/co/caprica/vlcj/component/EmbeddedMediaPlayerComponen"

**Comment by calmlotus** [comment]
@mlop113 did you find the solution for the NoClassDefFoundError you had? I have the same issue, so I am wondering how you handled it to fix..

**Comment by caprica** [comment]
@calmlotus the best way to use vlcj-player is to "git clone" the project and import the pom.xml into IntelliJ IDEA (or Eclipse I suppose) as a Maven project.

Make sure you use the "master" branch if you're using vlcj-4, or the vlcj-3.x branch if you're using vlcj-3.

**Comment by calmlotus** [comment]
@caprica Thanks for the quick response. Unfortunately I'm not using IDE and just working using the shell and vi. I wanted to check simple java code to play a video at the specified path from the shell on Mac.
I'd appreciate it if you would suggest any simple way or example to do that..

**Comment by caprica** [comment]
If you're not using an IDE (well, why not?!), then install Maven and use that.

You will have to set a proper class-path yourself if you don't use an IDE.

Regarding playback on OSX - vlcj-player won't help you there because on OSX there is no heavyweight AWT for any JDK after 1.6. You would need to look at either "DirectMediaPlayer" in vlcj-3.x, or EmbeddedMediaPlayer with a CallbackVideoSurface in vlcj-4. There are examples for both in the vlcj test sources.

**Comment by calmlotus** [comment]
@caprica Thank you! I'll check it out... :)
