### ISSUE TITLE
Cannot launch VlcjPlayer - NullPointerException on AudioDeviceMenu.java file

### ISSUE THREAD

**Issue by khalidcawl** [caprica/vlcj-player#4]
I have downloaded, compiled, and ran the VlcjPlayer application from this link: https://github.com/caprica/vlcj-player. However, it throws the following exception when I launch it in Eclipse:

2015-12-09 16:00:21 INFO                            Info:77   - vlcj: 3.6.0
2015-12-09 16:00:21 INFO                            Info:78   - java: 1.8.0_66 Oracle Corporation
2015-12-09 16:00:21 INFO                            Info:79   - java home: /usr/lib/jvm/java-8-oracle/jre
2015-12-09 16:00:21 INFO                            Info:80   - os: Linux 3.19.0-37-generic amd64
2015-12-09 16:00:21 INFO                 NativeDiscovery:121  - Discovery found libvlc at '/usr/lib'
2015-12-09 16:00:22 INFO                   LibVlcFactory:171  - vlc: 2.1.6 Rincewind, changeset 2.1.6-0-gea01d28
2015-12-09 16:00:22 INFO                   LibVlcFactory:172  - libvlc: /usr/lib/libvlc.so.5.4.0
2015-12-09 16:00:24 WARN              DefaultMediaPlayer:921  - Audio output device enumeration requires libvlc 2.2.0 or later
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at uk.co.caprica.vlcjplayer.view.main.AudioDeviceMenu.onCreateMenu(AudioDeviceMenu.java:48)
    at uk.co.caprica.vlcjplayer.view.OnDemandMenu.<init>(OnDemandMenu.java:43)
    at uk.co.caprica.vlcjplayer.view.OnDemandMenu.<init>(OnDemandMenu.java:35)
    at uk.co.caprica.vlcjplayer.view.main.AudioDeviceMenu.<init>(AudioDeviceMenu.java:41)
    at uk.co.caprica.vlcjplayer.view.main.MainFrame.<init>(MainFrame.java:316)
    at uk.co.caprica.vlcjplayer.VlcjPlayer.<init>(VlcjPlayer.java:107)
    at uk.co.caprica.vlcjplayer.VlcjPlayer$1.run(VlcjPlayer.java:83)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I don't know what is the cause of the problem. Any help?

**Comment by khalidcawl** [comment]
I have figured out the solution. The problem was that I had VLC 2.1.6 on my ubuntu machine. When I updated my VLC to 2.2.1 it worked perfectly!!

**Comment by caprica** [comment]
Yeah, those audio device functions are not available in earlier versions of libVLC. Still probably should not null pointer though.

**Comment by khalidcawl** [comment]
I have actually tried to return from the method if that function returns null. But I ran into another problem: "Equalizer is not available, you need libvlc 2.2.0 or later" which lead me to this issue: https://github.com/caprica/vlcj/issues/248. From there I realized I need to update my VLC. It was all your help. Thanks a bunch!!
